"""Last-point-before-transport barrier against internal content leaking into
a client-facing WhatsApp send.

Built fresh here: the "V2 candidate" with `output_safe` in
services/whatsapp_control_io.py mentioned in the review does not exist in
the running production backend (confirmed against a `docker commit`
snapshot of the live container) or in any branch of this repository --
there was nothing in production to "reuse and verify". The V2 candidate
ZIP (separate, not implanted) does contain a `services/whatsapp_control_io.py`
with its own `output_safe`; this module does not adopt that file wholesale
(it carries a much larger pause/scope/concurrency system -- claim_send,
alert_claim, revision-based staleness checks -- out of scope for this
round and not duplicated here) but DOES merge its one check this module
was missing: a reply falsely claiming "ele/Dario já viu/leu sua mensagem"
(an unverifiable claim the review explicitly prohibits). The marker
pattern here was also simplified to match V2's unanchored-substring
approach, which is more robust than this module's original bracket-anchored
regex (it does not need separate handling for "[ audio enviado..." with an
internal space after the bracket).

Design, per the incident evidence (job 20585 / message 9194, where a reply
job's payload literally contained
"[Áudio enviado pelo proprietário desta conta nesta conversa]"):

  - This must be the LAST check before a send, applied to every path that
    can reach `whatsapp.send_text` -- not a prompt-side instruction to the
    model (models don't reliably follow those) and not a check only in one
    caller (jobs/handlers.py has at least two: process_inbound_whatsapp_message
    and twin_autopilot_check, plus whatsapp.send_text itself as the single
    place every path converges on -- see the integration note at the
    bottom of this file).
  - A match blocks the WHOLE message, not just the matched substring. A
    half-sent reply with the marker silently stripped still leaks context
    ("...nesta conversa] Pode me ligar?" minus the bracket is still a non
    sequitur, and a smarter leak might not be bracket-shaped at all) --
    and a partial send is harder to audit than a clean block.
  - Must survive accent/whitespace variation (the marker is generated by
    our own code with a fixed accent/spacing today, but a future revision,
    an LLM paraphrase of it, or a second marker elsewhere should not
    silently bypass this).
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from orchestrator.twin_risk_gate import normalize_text


@dataclass(frozen=True)
class OutputSafetyResult:
    safe: bool
    reason: str = ""  # objective, loggeable -- never the message content itself


# Internal markers that must never reach a client. Matched against
# normalize_text's accent-stripped/lowercased/whitespace-collapsed output,
# so "[Áudio  enviado..." / "[audio enviado..." / extra spacing all hit the
# same pattern. Each pattern is the STABLE PREFIX of a known internal
# annotation -- deliberately not the full bracketed string, so a future
# edit to the trailing wording (e.g. the "sem transcrição disponível"
# variant) does not silently stop matching.
_INTERNAL_MARKER_PATTERNS: tuple[re.Pattern[str], ...] = (
    # Plain substring, not anchored to a leading "[": more robust than an
    # opening-bracket anchor (which still needs separate whitespace
    # handling -- see the V2 candidate's services/whatsapp_control_io.py,
    # whose `output_safe` checks this same substring unanchored; merged
    # here rather than duplicated as a second, slightly different pattern).
    re.compile(r"audio enviado pelo proprietario"),
    re.compile(r"audio de saida desta conta"),
    re.compile(r"mensagem enviada pelo proprietario"),
    # Generic shape for any future "[<label> interno/sistema ...]" marker,
    # kept intentionally narrow to the words that only ever appear in our
    # own control annotations, not in ordinary client-facing text.
    re.compile(r"\[\s*(?:marcador|contexto|sistema|interno)\b"),
)

# An unverifiable claim that the owner already saw/read the client's
# message -- the review's own instruction: "não alegar que alguém viu uma
# mensagem sem evidência". From the V2 candidate's output_safe; merged
# here rather than left as a second, separate safety function.
_FALSE_READ_CLAIM_PATTERN = re.compile(
    r"\b(?:ele|dario)\s+(?:ja\s+)?(?:viu|leu)\s+(?:a\s+)?sua\s+mensagem\b"
)

# A system/role instruction leaking verbatim (e.g. the persona prompt's own
# section headers) rather than the model's actual reply.
_SYSTEM_LEAK_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^\s*voce\s+e\s+o\s+(?:assistente|gemeo|twin)\b"),
    re.compile(r"instrucoes?\s+(?:internas?|de\s+sistema)\b"),
    re.compile(r"\bmanual\s+(?:interno|operacional|tecnico)\s+(?:do|da|de)\b"),
)

# Recognizable API-key shapes. Narrow on purpose: this blocks the message,
# it never logs or reproduces the matched value (see redact() below) and it
# is not a credential scanner for the codebase -- see services/log_redaction.py
# and the separate protection/redaction plan requested for the two possible
# keys found in the 08/10 review (8793, 8734), which this module does not
# attempt to resolve on its own.
_CREDENTIAL_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"sk-or-v1-[a-z0-9]{20,}"),  # OpenRouter
    re.compile(r"sk-[a-z0-9]{32,}"),  # OpenAI/DeepSeek-style
    re.compile(r"\bAIza[0-9A-Za-z_-]{30,}\b"),  # Google API key shape
)


def output_safe(reply: str) -> OutputSafetyResult:
    """Call this immediately before any WhatsApp send -- see the module
    docstring for why it must be the last check, not a prompt instruction.
    `reason` is an objective category string for logging, never the
    message content (services/audit.py's record_log already enforces not
    copying full message bodies; this keeps the same discipline)."""
    if not reply or not reply.strip():
        return OutputSafetyResult(safe=True)
    normalized = normalize_text(reply)
    for pattern in _INTERNAL_MARKER_PATTERNS:
        if pattern.search(normalized):
            return OutputSafetyResult(safe=False, reason="internal_marker")
    if _FALSE_READ_CLAIM_PATTERN.search(normalized):
        return OutputSafetyResult(safe=False, reason="unverifiable_read_claim")
    for pattern in _SYSTEM_LEAK_PATTERNS:
        if pattern.search(normalized):
            return OutputSafetyResult(safe=False, reason="system_instruction_leak")
    for pattern in _CREDENTIAL_PATTERNS:
        if pattern.search(reply):  # case-sensitive: keys are case-sensitive
            return OutputSafetyResult(safe=False, reason="credential_pattern")
    return OutputSafetyResult(safe=True)


# --- Integration note (not executed here; no app/DB available in this
# sandbox -- see the delivery message for what was reviewed-but-not-run) ---
#
# jobs/handlers.py has three places that enqueue whatsapp.send_text with
# model- or pipeline-generated content: process_inbound_whatsapp_message
# (lines ~241, ~298) and twin_autopilot_check (line ~370, the non-risky
# branch -- the risky branch sends the hardcoded TWIN_HOLDING_MESSAGE,
# which cannot carry a leaked marker). All three, plus any future caller,
# converge on send_whatsapp_text (line 116) before the provider call --
# that is the one chokepoint that actually "covers all send paths"
# (the mission's explicit requirement), not each individual caller:
#
#   async def send_whatsapp_text(db: AsyncSession, payload: dict) -> None:
#       ...
#       content = str(payload['content'])
#       instance = payload.get('instance') or None
#       if not await _owner_audio_send_guard(db, payload, to, instance):
#           return
#       result = output_safe(content)
#       if not result.safe:
#           await record_log(
#               db, source="output_safety", level="error",
#               message="Envio bloqueado: conteúdo não seguro para transporte",
#               payload={"to_redacted": to[-4:], "reason": result.reason,
#                        "job_payload_keys": sorted(payload.keys())},
#           )
#           return  # no retry, no second automatic message explaining the block
#       provider = get_whatsapp_provider()
#       ...
#
# This also covers retries and re-queued jobs for free: the check runs
# every time this handler executes, including on a retry of an old job
# whose payload was generated before this fix existed.
