"""Shared reader for the build-time VERSION.json (generated by the release
process, see RC1_AUDIT.md / RELEASE_NOTES.md). Standalone (no import of
utils.config) so both config.py (app_version's default) and
observability/version.py (the /api/version endpoint) can read it without a
circular import.
"""

import json
from functools import lru_cache
from pathlib import Path

_VERSION_FILE = Path(__file__).resolve().parent.parent / "VERSION.json"


@lru_cache(maxsize=1)
def read_version_file() -> dict:
    """Cached — VERSION.json is a build artifact, fixed for the life of the
    running process. Falls back to an honest "unknown" payload rather than
    raising when running from source without a generated VERSION.json (e.g.
    local dev)."""
    try:
        return json.loads(_VERSION_FILE.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return {
            "version": "unknown",
            "commit": "unknown",
            "buildDate": None,
            "releaseType": "unknown",
        }
