global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'darioos-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    scheme: http
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
