"""google drive accounts and indexed files

Revision ID: 0e6459491047
Revises: 61c82eeb3be5
Create Date: 2026-07-10 16:33:30.087817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0e6459491047"
down_revision: Union[str, None] = "61c82eeb3be5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "google_drive_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("account_label", sa.String(length=255), nullable=False),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_gdrive_account_user_provider"
        ),
    )
    op.create_index(
        op.f("ix_google_drive_accounts_user_id"),
        "google_drive_accounts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "google_drive_indexed_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(length=255), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("modified_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("embedding_ids", sa.JSON(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "file_id", name="uq_gdrive_indexed_file_user_file"
        ),
    )
    op.create_index(
        op.f("ix_google_drive_indexed_files_user_id"),
        "google_drive_indexed_files",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_google_drive_indexed_files_user_id"),
        table_name="google_drive_indexed_files",
    )
    op.drop_table("google_drive_indexed_files")
    op.drop_index(
        op.f("ix_google_drive_accounts_user_id"), table_name="google_drive_accounts"
    )
    op.drop_table("google_drive_accounts")
    # ### end Alembic commands ###
