"""google calendar and contacts accounts

Revision ID: 61c82eeb3be5
Revises: 8d535824ec8f
Create Date: 2026-07-10 14:38:53.255508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61c82eeb3be5'
down_revision: Union[str, None] = '8d535824ec8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_gcalendar_account_user_provider')
    )
    op.create_index(op.f('ix_google_calendar_accounts_user_id'), 'google_calendar_accounts', ['user_id'], unique=False)
    op.create_table('google_contacts_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_gcontacts_account_user_provider')
    )
    op.create_index(op.f('ix_google_contacts_accounts_user_id'), 'google_contacts_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_contacts_accounts_user_id'), table_name='google_contacts_accounts')
    op.drop_table('google_contacts_accounts')
    op.drop_index(op.f('ix_google_calendar_accounts_user_id'), table_name='google_calendar_accounts')
    op.drop_table('google_calendar_accounts')
    # ### end Alembic commands ###
