"""unique constraint on messages external_id

Revision ID: abb2a2bf950e
Revises: 790826c45a84
Create Date: 2026-07-10 01:27:37.044717

"""

from typing import Sequence, Union

from alembic import op


revision: str = "abb2a2bf950e"
down_revision: Union[str, None] = "790826c45a84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_external_id"), table_name="messages")
    op.create_index(
        op.f("ix_messages_external_id"), "messages", ["external_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_external_id"), table_name="messages")
    op.create_index(
        op.f("ix_messages_external_id"), "messages", ["external_id"], unique=False
    )
    # ### end Alembic commands ###
