"""message provider_timestamp and delivery_status

Revision ID: d3e16cbf2688
Revises: abb2a2bf950e
Create Date: 2026-07-10 02:05:17.940488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3e16cbf2688'
down_revision: Union[str, None] = 'abb2a2bf950e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('delivery_status', sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='messagedeliverystatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'delivery_status')
    op.drop_column('messages', 'provider_timestamp')
    # ### end Alembic commands ###
